#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$ROOT_DIR/apps/web"
BASE_URL="${CLOAKBROWSER_BASE_URL:-https://cloakbrowser.org}"

cd "$ROOT_DIR"

if ! command -v pnpm >/dev/null 2>&1; then
  echo "pnpm is required." >&2
  exit 1
fi

if grep -q 'replace-with-cloudflare-d1-database-id' "$WEB_DIR/wrangler.toml"; then
  echo "apps/web/wrangler.toml still contains the placeholder D1 database_id." >&2
  echo "Create the D1 database and replace database_id before deploying." >&2
  exit 1
fi

echo "== Cloudflare identity =="
(cd "$WEB_DIR" && pnpm exec wrangler whoami)

echo "== Required Worker secrets =="
if ! (cd "$WEB_DIR" && pnpm exec wrangler secret list | grep -q 'REPORT_HASH_SECRET'); then
  echo "REPORT_HASH_SECRET is not configured as a Cloudflare Worker secret." >&2
  echo "Run: cd apps/web && pnpm exec wrangler secret put REPORT_HASH_SECRET" >&2
  exit 1
fi

echo "== CI checks =="
pnpm run ci

if [[ ! -f "$WEB_DIR/dist/_worker.js/scheduled-worker.js" ]]; then
  echo "Scheduled Worker wrapper was not generated by the web build." >&2
  exit 1
fi

echo "== D1 migrations =="
(cd "$WEB_DIR" && pnpm exec wrangler d1 migrations apply browser_fidelity_reports --remote)

echo "== D1 expired report purge =="
NOW_ISO="$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")"
(cd "$WEB_DIR" && pnpm exec wrangler d1 execute browser_fidelity_reports --remote --command "DELETE FROM reports WHERE expires_at <= '$NOW_ISO'")

echo "== Cloudflare deploy =="
(cd "$WEB_DIR" && pnpm exec wrangler deploy)

echo "== Production smoke =="
CLOAKBROWSER_BASE_URL="$BASE_URL" node "$ROOT_DIR/scripts/smoke-production.mjs"

echo "== Cloudflare log tail sample =="
echo "Open a second terminal for continuous logs when needed:"
echo "  cd apps/web && pnpm exec wrangler tail browser-fidelity-lab --format=json"
