import type { BrowserFidelityPreset } from "./types";

export const presets: BrowserFidelityPreset[] = [
  {
    id: "pixel-8-us",
    label: "Pixel 8 - US English",
    deviceName: "Pixel 8",
    region: "US",
    tags: ["mobile", "android", "chromium", "us"],
    browserName: "chromium",
    userAgent:
      "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36",
    viewport: { width: 412, height: 915 },
    screen: { width: 412, height: 915 },
    deviceScaleFactor: 2.625,
    isMobile: true,
    hasTouch: true,
    locale: "en-US",
    timezoneId: "America/New_York",
    geolocation: { latitude: 40.7128, longitude: -74.006 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Use with a US egress IP for geography consistency."]
  },
  {
    id: "iphone-15-us",
    label: "iPhone 15 - US English",
    deviceName: "iPhone 15",
    region: "US",
    tags: ["mobile", "iphone", "webkit", "us"],
    browserName: "webkit",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1",
    viewport: { width: 393, height: 852 },
    screen: { width: 393, height: 852 },
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    locale: "en-US",
    timezoneId: "America/Los_Angeles",
    geolocation: { latitude: 37.7749, longitude: -122.4194 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Use WebKit when validating iOS Safari behavior."]
  },
  {
    id: "desktop-chrome-us",
    label: "Desktop Chrome - US English",
    deviceName: "Desktop Chrome",
    region: "US",
    tags: ["desktop", "chromium", "us"],
    browserName: "chromium",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    viewport: { width: 1440, height: 900 },
    screen: { width: 1440, height: 900 },
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    locale: "en-US",
    timezoneId: "America/New_York",
    geolocation: { latitude: 40.7128, longitude: -74.006 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Good baseline for desktop QA and CI smoke checks."]
  },
  {
    id: "desktop-firefox-gb",
    label: "Desktop Firefox - UK English",
    deviceName: "Desktop Firefox",
    region: "GB",
    tags: ["desktop", "firefox", "gb", "eu"],
    browserName: "firefox",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.4; rv:124.0) Gecko/20100101 Firefox/124.0",
    viewport: { width: 1366, height: 768 },
    screen: { width: 1366, height: 768 },
    deviceScaleFactor: 1,
    isMobile: false,
    hasTouch: false,
    locale: "en-GB",
    timezoneId: "Europe/London",
    geolocation: { latitude: 51.5072, longitude: -0.1276 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Use with a UK egress IP when checking locale and timezone."]
  },
  {
    id: "android-tokyo",
    label: "Android Chrome - Japanese",
    deviceName: "Android Mobile",
    region: "JP",
    tags: ["mobile", "android", "chromium", "jp", "asia"],
    browserName: "chromium",
    userAgent:
      "Mozilla/5.0 (Linux; Android 14; SM-S921B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36",
    viewport: { width: 384, height: 854 },
    screen: { width: 384, height: 854 },
    deviceScaleFactor: 2.75,
    isMobile: true,
    hasTouch: true,
    locale: "ja-JP",
    timezoneId: "Asia/Tokyo",
    geolocation: { latitude: 35.6762, longitude: 139.6503 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Use with a Japan egress IP for region consistency checks."]
  },
  {
    id: "desktop-webkit-us",
    label: "Desktop WebKit - US English",
    deviceName: "Desktop Safari",
    region: "US",
    tags: ["desktop", "webkit", "safari", "us"],
    browserName: "webkit",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    viewport: { width: 1440, height: 900 },
    screen: { width: 1440, height: 900 },
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    locale: "en-US",
    timezoneId: "America/Los_Angeles",
    geolocation: { latitude: 37.7749, longitude: -122.4194 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Use WebKit for Safari-oriented desktop QA."]
  },
  {
    id: "iphone-15-gb",
    label: "iPhone 15 - UK English",
    deviceName: "iPhone 15",
    region: "GB",
    tags: ["mobile", "iphone", "webkit", "gb", "eu"],
    browserName: "webkit",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1",
    viewport: { width: 393, height: 852 },
    screen: { width: 393, height: 852 },
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    locale: "en-GB",
    timezoneId: "Europe/London",
    geolocation: { latitude: 51.5072, longitude: -0.1276 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Use with a UK egress IP when validating iOS Safari regional behavior."]
  },
  {
    id: "desktop-chrome-de",
    label: "Desktop Chrome - German EU",
    deviceName: "Desktop Chrome",
    region: "DE",
    tags: ["desktop", "chromium", "de", "eu"],
    browserName: "chromium",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    viewport: { width: 1440, height: 900 },
    screen: { width: 1440, height: 900 },
    deviceScaleFactor: 2,
    isMobile: false,
    hasTouch: false,
    locale: "de-DE",
    timezoneId: "Europe/Berlin",
    geolocation: { latitude: 52.52, longitude: 13.405 },
    permissions: ["geolocation"],
    colorScheme: "light",
    notes: ["Use with an EU egress IP for locale and timezone consistency checks."]
  }
];

export function getPreset(id: string): BrowserFidelityPreset | undefined {
  return presets.find((preset) => preset.id === id);
}
